### ISSUE TITLE
Frequently stops steaming after about 20-30 minutes

### ISSUE THREAD

**Issue by Robiullah2244** [tritondigital/player-sdk#38]
The audio stream URL returns 404 Not Found("Invalid or expired Session ID") after about 20-30 minutes of play and the audio is paused. When I play this audio again, I see the URL has changed.

So can you please help me to fix the "Invalid or expired Session ID" issue from my side?

**Comment by jd-buys** [comment]
@Robiullah2244 How long did you pause the stream?

**Comment by jd-buys** [comment]
@Robiullah2244 Sorry for only getting back to you now. Do you maybe have a link that I can test and help debug the issue?

**Comment by Robiullah2244** [comment]
@jd-buys, You can test with this link:
https://25703.live.streamtheworld.com/AFNE_AVNAAC.aac?csegid=1&country=IT&tdsdk=js-2.9&swm=false&pname=TDSdk&pversion=2.9&banners=none&burst-time=15&sbmid=7166a43c-dd4a-4934-bb93-ba0ff8200543

**Comment by jd-buys** [comment]
@Robiullah2244 Do you maybe have the app/site that I can test with.

**Comment by Robiullah2244** [comment]
@jd-buys, https://afngo.net/afneurope/Aviano/radio/Aviano

**Comment by jd-buys** [comment]
@Robiullah2244 I have listened to the stream multiple times for well over 3 hours without any issues.
The one time I had an issue was when I had a network error, but the stream reconnected and worked fine.

Can you maybe export a HAR of the network calls to help me maybe see the issue and debug it, because I can't replicate the issue so far.
